### ISSUE TITLE
[feature request] stop spinner with a success or error state

### ISSUE THREAD

**Issue by samuela** [fadeevab/cliclack#10]
It would be handy if there was a way to stop a spinner with a failure state. From a UI perspective that makes it clear in which task the failure occurred. AFAICT there is not currently a way to stop a spinner on anything besides the default stopping state.

**Comment by fadeevab** [comment]
@samuela Like this?
```rust
let mut spinner = cliclack::spinner();
spinner.start("Installing via pnpm");
if ok {
    spinner.stop("Installed via pnpm");
} else {
    spinner.error("Installation failed");
}
```

**Comment by samuela** [comment]
oh nice! somehow i missed that!

**Comment by fadeevab** [comment]
@samuela You haven't missed, it doesn't exist YET, I was just thinking how would it look like :)

**Comment by samuela** [comment]
ah i see... yeah i think that would be fine. also if there was a way to clear a spinner from the screen, users could simply use whatever `cliclack::log::*` function suits their needs

**Comment by fadeevab** [comment]
@samuela  I'll check it out tomorrow then release all new features

**Comment by fadeevab** [comment]
Done

**Comment by fadeevab** [comment]
@samuela `cliclack 0.1.11` published, cheers!

**Comment by samuela** [comment]
Woohoo! Thanks @fadeevab  -- Can't wait to upgrade !
