### ISSUE TITLE
`cliclack::note` does not respect terminal width

### ISSUE THREAD

**Issue by samuela** [fadeevab/cliclack#11]
<img width="1507" alt="Screenshot 2024-01-11 at 8 22 43 PM" src="https://github.com/fadeevab/cliclack/assets/226872/98ff4e27-f901-435f-a90b-f9f636a4e055">

**Comment by fadeevab** [comment]
@samuela The code is supposed to be very simple and even stupid to an extent. I will think whether it could be more or less easily fixed.

**Comment by samuela** [comment]
yeah, i hear that. agreed that it's not a major issue imho. users can always work around it with eg the `textwrap` crate

**Comment by fadeevab** [comment]
As auto-wrap is not planned, I close the issue, unless of severe demand.
