### ISSUE TITLE
`cliclack::note` does not correctly calculate text width when handling ANSI escape codes and emojis

### ISSUE THREAD

**Issue by samuela** [fadeevab/cliclack#12]
For example

<img width="1512" alt="Screenshot 2024-01-11 at 9 21 22 PM" src="https://github.com/fadeevab/cliclack/assets/226872/2300f0bb-f5c3-439d-94a8-3b743f81b37d">

I believe the issue lies in https://github.com/fadeevab/cliclack/blob/e026f3c83beb90ea48cb87e7ef909fd1be6ee2a5/src/theme.rs#L485-L488 and surrounding code. The textwrap crate has functions for calculating text width that could be leveraged: https://docs.rs/textwrap/latest/textwrap/core/fn.display_width.html.

**Comment by fadeevab** [comment]
@samuela Gotcha. Let's fix it after merging your PRs and validation improving.
