### ISSUE TITLE
Cursor remains hidden at the end of interactive mode

### ISSUE THREAD

**Issue by jayv** [fadeevab/cliclack#2]
Thx for this small lib!

I've noticed that every time I enter interactive mode my cursor goes missing on my terminal.

I can restore it by resetting my terminal (`reset`) after the process ends or calling `console::Term::stdout().show_cursor()?;` from my code, but it would be nice if this wasn't an issue.

**Comment by fadeevab** [comment]
@jayv Hi! Sorry, missed your message, I'll check it out.

**Comment by fadeevab** [comment]
@jayv Fixed partially. Try using `cliclack 0.1.9` which is just published, and also, use ESC to cancel the interaction. What's not covered yet: `Ctrl+C`. It's because I'm using `console` crate (the same which is used by `dialoguer`), and this crate hides handling `Ctrl+C` under the hood.

**Comment by jayv** [comment]
Will TAL, I managed to handle the `ctrl-c` case by registering my own signal handler, that said probably not something a library should do anyway. Have you considered `crossterm` ? It seems quite popular with the more advanced TUI libs.

**Comment by jayv** [comment]
Seems to work! 👍🏻

**Comment by fadeevab** [comment]
@jayv I think about an option to register a signal handler before interaction (stacking with the old signal handler) and deregister after. I think I would experiment later or wait until someone complains about it :)
