### ISSUE TITLE
[feature request] better support for multiline text

### ISSUE THREAD

**Issue by cylewitruk** [fadeevab/cliclack#20]
Hi!

Loving cliclack so far, it's a very refreshing look compared to some of the other prompt frameworks :)

One thing I'm missing is better support for multiline text (where there's newlines) and subheadings, both of these in the "log" module. Newlines at the moment break the line on the left, and there's no other way that I can find (built-in) to support sub-headings. For now I'm solving this by printing the `│` myself and aligning the text manually, which works, but it's not very clean :)

Edit: this does already work with `log::remark`, so I'm guessing it should be pretty straightforward? It does not work with, for example: `intro` or `confirm`.

**Comment by fadeevab** [comment]
@cylewitruk Log functions handle multilining like I mentioned here https://github.com/fadeevab/cliclack/issues/22#issuecomment-2023035108, do you mean you'd like to see multiline support in the other prompts?

**Comment by cylewitruk** [comment]
> @cylewitruk Log functions handle multilining like I mentioned here [#22 (comment)](https://github.com/fadeevab/cliclack/issues/22#issuecomment-2023035108), do you mean you'd like to see multiline support in the other prompts?

Yeah, exactly -- I think it's probably more that I want "sub-headings" and/or "extra help text", which may include multiline.

**Comment by fadeevab** [comment]
Merged to `main`

**Comment by cylewitruk** [comment]
> Merged to `main`

🤙🥳
