### ISSUE TITLE
[feature request] progress bars

### ISSUE THREAD

**Issue by cylewitruk** [fadeevab/cliclack#21]
We have the spinner which works well, but it would be awesome to also have a progressbar :smile:  Maybe an integration with `indicatif` that automatically sets indicatif styling based on the cliclack theme and sets the prefix characters so that the '│` on the left doesn't break? That would be awesome -- but realistically I'd be overjoyed with just a simple progress+download bar built-in and drop indicatif vs. having to hack up indicatif templates/styling to not break the cliclack look.

EDIT: Aha, and I just noticed that cliclack is already using indicatif.. so we're half way there! :smile: I'm pretty swamped atm, but if you guys don't have time in the near future to look at these I'd be happy to PR some of my feature requests when I get some downtime.

**Comment by cylewitruk** [comment]
P.S. I really wanted this, so I've added both progress+download bars -- will send up a PR for scrutiny shortly :smile:

**Comment by fadeevab** [comment]
> P.S. I really wanted this, so I've added both progress+download bars -- will send up a PR for scrutiny shortly 😄

Good! Btw, you can see that `indicatif` is already used, so you can re-use it for progress bars as well.

**Comment by cylewitruk** [comment]
> > P.S. I really wanted this, so I've added both progress+download bars -- will send up a PR for scrutiny shortly 😄
> 
> Good! Btw, you can see that `indicatif` is already used, so you can re-use it for progress bars as well.

Yup, noticed that, makes it very simple :)

**Comment by cylewitruk** [comment]
Closing this as #23 and #27 are closed :rocket:

**Comment by fadeevab** [comment]
@cylewitruk `0.1.14` has published 🎉
