### ISSUE TITLE
[Bug] Crash in `select` component when no items added

### ISSUE THREAD

**Issue by cylewitruk** [fadeevab/cliclack#29]
Looks like there could be better handling when the list is empty (which can easily happen when populated from a db etc.). Maybe even a default (but customizable) "There are no items available" text. This was with an empty list and pressing `<enter>`.

![image](https://github.com/fadeevab/cliclack/assets/35576205/039865aa-9fb6-4328-8431-dfb905fc676a)

EDIT: This also shows up with other interactions, such as up/down arrows:
![image](https://github.com/fadeevab/cliclack/assets/35576205/3cdb1db8-ec58-4876-add2-c3f8b53fa8ec)

I think the biggest crux here is simply defining what the default behavior should be for empty-lists... i.e. should zero-lists panic already in `interact()` (with a proper error message) and force consumers to length-check before trying to show an empty list?

**Comment by cylewitruk** [comment]
Leaning towards panic in `interact()` with some documentation on `select` regarding behavior when the list is empty. It's too hard (for a framework) to know the intent of the consumer if a list should be empty and how that should be presented (if at all) to the user.

**Comment by fadeevab** [comment]
@cylewitruk It probably makes sense to add `panic` at the beginning of the `interact()` method because the `select` without items is not supposed to exist.

**Comment by fadeevab** [comment]
@cylewitruk There was an error enum, however, it was reduced at the early stage because it contained `std::io` errors only. Custom error kind can be returned anyways.

**Comment by fadeevab** [comment]
@cylewitruk  PR #37  https://github.com/fadeevab/cliclack/pull/37/files

**Comment by fadeevab** [comment]
@cylewitruk Fixed in `v0.2.5`. Thanks!
