### ISSUE TITLE
[thought] context/state-aware `clack` type for managing sequences

### ISSUE THREAD

**Issue by cylewitruk** [fadeevab/cliclack#30]
Today I came across the thought that it would actually be nice to have a context-aware `Clack` (or whatever) type where state can be maintained throughout a longer dialogue sequence.

Something like:

```rust
let clack = Clack;
clack.intro("We're gonna do some stuff!");
clack.select("Please choose something!").from(["Eenie", "Meenie", "Miney", "Mo"]).interact()?;
clack.outro("We're done!");
```

This doesn't say much in itself, but allowing components to be aware of where they are in the chain (automatically) would make some conditional rendering possible based on last state.

**Comment by fadeevab** [comment]
@cylewitruk How is your example different from what is there now?

```rust
intro("We're gonna do some stuff!");
select("Please choose something!").from(["Eenie", "Meenie", "Miney", "Mo"]).interact()?;
outro("We're done!");
```

**Comment by cylewitruk** [comment]
> @cylewitruk How is your example different from what is there now?
> 
> ```rust
> intro("We're gonna do some stuff!");
> select("Please choose something!").from(["Eenie", "Meenie", "Miney", "Mo"]).interact()?;
> outro("We're done!");
> ```

The example doesn't give context -- but where it becomes useful is when everything doesn't necessarily happen within the same function.

Upon further reflection this could also be the basis for introducing the builder pattern for forms.

This issue is mostly a discussion topic for me -- but discussions aren't enabled for this repo 😊

**Comment by fadeevab** [comment]
@cylewitruk This can implemented on your own as a wrapper based on `cliclack`. It should not be in the crate.
