### ISSUE TITLE
[bug] Regression in MultiProgress symbols

### ISSUE THREAD

**Issue by cylewitruk** [fadeevab/cliclack#36]
In my other screenshot in #33 I had hollow green diamonds.  Same code is now producing solid cyan diamonds:

![image](https://github.com/fadeevab/cliclack/assets/35576205/58fc1ca9-567c-4fae-a763-2e671be79b9c)

**Comment by fadeevab** [comment]
@cylewitruk True. Gonna fix  that

**Comment by fadeevab** [comment]
@cylewitruk I forced pushed (I messed up with a commit message)... check it out

**Comment by cylewitruk** [comment]
> @cylewitruk I forced pushed (I messed up with a commit message)... check it out

Afk now but will check it out tomorrow! 🙏

**Comment by cylewitruk** [comment]
@fadeevab looks good now! I think this is turning out to be a pretty nice component tbh :)

**Comment by fadeevab** [comment]
@cylewitruk YES

**Comment by fadeevab** [comment]
Published `v0.2.4`.
