### ISSUE TITLE
[feature request] validation on every input change, not just when enter is pressed

### ISSUE THREAD

**Issue by samuela** [fadeevab/cliclack#4]
I would love to be able to have a more interactive, immediate UX. Perhaps for slower validations it could also be configured to validate on enter and show a spinner?

**Comment by fadeevab** [comment]
@samuela Seems like, it is super easy to do having the current code organization. As an experiment, I just moved out the validation out of the "press Enter" condition, and it works. The question would be choosing a default behavior: should it be so by default? Both cases might be useful, maybe some config or method name is needed (`validate`/`validate_on_enter`)

**Comment by samuela** [comment]
> (validate/validate_on_enter)

ooh yeah i like that! i can totally foresee both situations being useful, eg. checking that an email is valid => `validate`. Checking that a username is not already taken in the database => `validate_on_enter`.

**Comment by fadeevab** [comment]
@samuela soon...

**Comment by fadeevab** [comment]
Done in PR#16
