### ISSUE TITLE
[problem] Issue when publishing a crate dependent on `cliclack`

### ISSUE THREAD

**Issue by cylewitruk** [fadeevab/cliclack#45]
This is the first time I try to publish a crate, so maybe I'm doing something wrong, but I'm getting the following error:

```
➜ cargo publish -p stackify-cli
    Updating crates.io index
error: all dependencies must have a version specified when publishing.
dependency `cliclack` does not specify a version
Note: The published dependency will use the version from crates.io,
the `git` specification will be removed from the dependency declaration.
```

@fadeevab anything you recognize?

**Comment by cylewitruk** [comment]
Realized I'm an idiot and it's because I was using a `git` reference instead of version :)

**Comment by fadeevab** [comment]
@cylewitruk yeap, I wanted to say your forgot to change the dependency :)
