### ISSUE TITLE
[bug] The GIF of multi-progress bars has a mistake of how they stop

### ISSUE THREAD

**Issue by fadeevab** [fadeevab/cliclack#46]
One guy found out how the bars stop at the demo:

![image](https://github.com/fadeevab/cliclack/assets/5967447/5536e173-4866-461d-8732-405e5d04571d)

A little mistake in the [multi-progress bars example](https://github.com/fadeevab/cliclack/blob/main/examples/multiprogress.rs) :)

**Comment by fadeevab** [comment]
@cylewitruk Everyone missed this :)

Fixed.

**Comment by cylewitruk** [comment]
@fadeevab awesome though that others are already starting to consume this functionality! 😄
