### ISSUE TITLE
[new feature] multi-lines Input

### ISSUE THREAD

**Issue by kingwingfly** [fadeevab/cliclack#50]
Current `Input` commits the msg once `Enter` is pressed. However, in some situations, we need `Enter` to start a new line just like  using an editor. In my case, I want to make a chatGPT dialog CLI tool, which needs inputting multi-lines to be sent to the API, it's naturally that I want to read multi-lines from terminal. 

`Enter` just submits the input content, while `Shift+Enter` not works either. 

# Expected
One of the two:

1. add `Input::new_line_keys_binding(&mut self, keys: Key)` to allow starting a new line.
2. new `MultilLineInput`, in which `CMD+Enter` on macOS or `Ctrl+Enter` on Windows to commit.

**Comment by kingwingfly** [comment]
I found it's nearly impossible with `console::Key`...

**Comment by fadeevab** [comment]
> I found it's nearly impossible with `console::Key`...

...and trying to move out from `console` crate makes things pretty complicated

**Comment by fadeevab** [comment]
Implemented in PR #54

**Comment by fadeevab** [comment]
@kingwingfly `cliclack v0.3.0` is alive!

![conspiracy-charlie-day](https://github.com/fadeevab/cliclack/assets/5967447/04adab84-8d2f-44bf-9263-a9ef0cd93cb4)

**Comment by kingwingfly** [comment]
Awesome！！

**Comment by kingwingfly** [comment]
@fadeevab I found that I was not included into contributor list properly. Maybe `@kingwingfly` should be removed from `Co-authored-by: Louis <836250617@qq.com> @kingwingfly`

**Comment by fadeevab** [comment]
> @fadeevab I found that I was not included into contributor list properly. Maybe `@kingwingfly` should be removed from `Co-authored-by: Louis <836250617@qq.com> @kingwingfly`

Right, fixed :)

**Comment by kingwingfly** [comment]
Thank you!
