### ISSUE TITLE
[bug] spinner `clear()` leaves artifacts when used in a procedural input flow

### ISSUE THREAD

**Issue by cylewitruk** [fadeevab/cliclack#65]
More of a nit than anything, but I think this gif makes it pretty clear what's being left behind. Ideally I would like it to be as-if the spinner never existed:

![spinner_clear](https://github.com/user-attachments/assets/23fe740b-26b3-4586-b0a6-ae14f148782e)

**Comment by fadeevab** [comment]
@cylewitruk The fix turns out to be pretty simple: #69

**Comment by cylewitruk** [comment]
> @cylewitruk The fix turns out to be pretty simple: #69 

Rediculously simple 😅 Good find, thanks!
