### ISSUE TITLE
[docs] Ensure code docs for all functions

### ISSUE THREAD

**Issue by cylewitruk** [fadeevab/cliclack#71]
Just something I noticed while grazing through the code, most methods are documented but there's a subset which are completely missing, like in `StringCursor` and in `filter.rs`. These should be documented to maintain the quality of the code docs :)

**Comment by fadeevab** [comment]
![oh-come-on](https://github.com/user-attachments/assets/031705cb-f41e-4509-ab48-a870bccb7219)

**Comment by fadeevab** [comment]
@cylewitruk submitted  https://github.com/fadeevab/cliclack/commit/3b3a43cd005bd83423cf80686e73a1ad2d666380
