### ISSUE TITLE
Option to display a message above a ProgressBar or MultiProgress

### ISSUE THREAD

**Issue by beeb** [fadeevab/cliclack#74]
Indicatif had a method named [`println`](https://docs.rs/indicatif/0.17.8/indicatif/struct.ProgressBar.html#method.println) which allows to print a message or log above the progress bar (or multiple progress bars).

In cliclack, consider the following example:

```rust
intro("Download")?;
let download = progress_bar(100).with_download_template();
download.start("Downloading, please wait...");
download.inc(10);
remark("Something")?;
download.inc(90);
download.stop("Downloaded");
outro("Done!")?;
```

In this case, the progress bar will be shown twice, once before the remark, and once after. I would like to avoid this duplication.

What's more, sometimes the progress bar display will actually render over the remark making it disappear.

Ideally, any call to a log function while a progress bar or multi is running would automatically be displayed above the bar(s).

**Comment by beeb** [comment]
@fadeevab would you accept something along those lines as a contribution?

https://github.com/fadeevab/cliclack/compare/main...beeb:cliclack:multi-println?expand=1

**Comment by fadeevab** [comment]
@beeb Hi! Thanks, yeah, it's likely to be accepted. Although, I don't get the idea of the `spacing` parameter: may the developer add '\n' at the end of the line where the spacing is needed?

**Comment by beeb** [comment]
Thanks for the quick reply. Indeed, adding a line return at the end would be an option but it would also add it to the last element, where as the spacing option only adds empty line _between_ the logs.

**Comment by fadeevab** [comment]
@beeb It looks like a corner case (from the crate's perspective): let's keep it as simple as indicatif's `println` is. You can add thebspacing logic on the side of your program (double-spacing, alternative spacing, etc.).

**Comment by beeb** [comment]
Thanks! Here it is https://github.com/fadeevab/cliclack/pull/75
